export function decodeEntities(s){return s.replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_,k)=>{const map={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};if(k[0]!=='#')return map[k.toLowerCase()]??_;const n=k[1]?.toLowerCase()==='x'?parseInt(k.slice(2),16):Number(k.slice(1));return Number.isInteger(n)&&n>=0&&n<=0x10ffff?String.fromCodePoint(n):'�'})}
export function parseHTML(input){
 const root={tag:'#root',attrs:{},children:[],text:''},stack=[root],nodes=[];let i=0;
 while(i<input.length){
 const container=stack.at(-1);
 if(['script','style','textarea','title'].includes(container.tag)){
   const endTag=new RegExp('</'+container.tag+'(?=[\\s/>])[^>]*>','ig');endTag.lastIndex=i;
   const end=endTag.exec(input),stop=end?end.index:input.length;
   const raw=input.slice(i,stop);
   container.children.push({text:['textarea','title'].includes(container.tag)?decodeEntities(raw):raw,children:[]});
   stack.pop();i=end?endTag.lastIndex:input.length;continue;
 }
 if(input.startsWith('<!--',i)){const end=input.indexOf('-->',i+4);if(end<0)throw Error('Nicht geschlossener HTML-Kommentar');i=end+3;continue}if(input[i]!=='<'){const end=input.indexOf('<',i),j=end<0?input.length:end;stack.at(-1).children.push({text:decodeEntities(input.slice(i,j)),children:[]});i=j;continue}
 let j=i+1,quote='';for(;j<input.length;j++){const ch=input[j];if(quote){if(ch===quote)quote=''}else if(ch==='"'||ch==="'")quote=ch;else if(ch==='>')break}if(j===input.length)throw Error('Unvollständiges HTML-Tag');const token=input.slice(i+1,j);i=j+1;if(token.startsWith('!')||token.startsWith('?'))continue;
 const m=/^\s*(\/?)\s*([A-Za-z][\w:-]*)([\s\S]*)$/.exec(token);if(!m)throw Error('Ungültiges HTML-Tag');const closing=!!m[1],tag=m[2].toLowerCase();if(closing){const at=stack.findLastIndex(n=>n.tag===tag);if(at>0)stack.length=at;continue}
 const attrs=Object.create(null),rest=m[3];let p=0;while(p<rest.length){while(/\s/.test(rest[p]??'')&&p<rest.length)p++;if(p>=rest.length||rest[p]==='/')break;const a=/^([^\s=/>]+)/.exec(rest.slice(p));if(!a)throw Error('HTML-Attribut ungültig');const key=a[1].toLowerCase();p+=a[0].length;while(p<rest.length&&/\s/.test(rest[p]))p++;let value='';if(rest[p]==='='){p++;while(p<rest.length&&/\s/.test(rest[p]))p++;if(rest[p]==='"'||rest[p]==="'"){const q=rest[p++],start=p;while(p<rest.length&&rest[p]!==q)p++;if(p===rest.length)throw Error('Attribut nicht geschlossen');value=rest.slice(start,p++)}else{const start=p;while(p<rest.length&&!/\s/.test(rest[p]))p++;value=rest.slice(start,p).replace(/\/$/,'')}}if(Object.hasOwn(attrs,key))throw Error('Doppeltes HTML-Attribut: '+key);attrs[key]=decodeEntities(value)}
 const node={tag,attrs,children:[],parent:stack.at(-1)};stack.at(-1).children.push(node);nodes.push(node);if(stack.length>200)throw Error('HTML überschreitet 200 Verschachtelungen');if(nodes.length>50000)throw Error('HTML überschreitet 50000 Elemente');if(!['area','base','br','col','embed','hr','img','input','link','meta','param','source','track','wbr'].includes(tag)&&!token.trimEnd().endsWith('/'))stack.push(node);
 }
 return {root,nodes};
}
export function nodeText(node){if(node.attrs?.['aria-hidden']==='true'||['script','style'].includes(node.tag))return '';if(node.tag==='img')return (node.attrs.alt??'').trim();return ((node.text??'')+(node.children??[]).map(nodeText).join(' ')).replace(/\s+/g,' ').trim()}
function accessibleName(node,nodes,allowContent=true){const a=node.attrs;if(a['aria-labelledby']){const text=a['aria-labelledby'].split(/\s+/).map(id=>nodes.find(n=>n.attrs.id===id)).filter(Boolean).map(nodeText).join(' ').trim();if(text)return text}if(a['aria-label']?.trim())return a['aria-label'].trim();return allowContent?nodeText(node):''}
export function checkHTML(input,rules,c){const {nodes}=parseHTML(input),out=[];const add=(rule,issues)=>out.push({rule,passed:issues.length===0,issues});
 for(const rule of rules){let issues=[];if(rule==='html-lang'){const n=nodes.find(n=>n.tag==='html');if(!n?.attrs.lang?.trim()||! /^[A-Za-z]{2,8}(?:-[A-Za-z0-9]{1,8})*$/.test(n.attrs.lang))issues.push('html benötigt nichtleeres syntaktisches lang-Attribut')}
 if(rule==='image-alt')nodes.filter(n=>n.tag==='img').forEach((n,i)=>{if(!Object.hasOwn(n.attrs,'alt'))issues.push('Bild '+(i+1)+' ohne alt; data-alt zählt nicht')});
 if(rule==='button-name')nodes.filter(n=>n.tag==='button').forEach((n,i)=>{if(!accessibleName(n,nodes))issues.push('Button '+(i+1)+' ohne erkennbaren Namen')});
 if(rule==='input-name')nodes.filter(n=>['input','select','textarea'].includes(n.tag)&&n.attrs.type!=='hidden').forEach((n,i)=>{const a=n.attrs;let text=accessibleName(n,nodes,false);if(!text&&a.id)text=nodes.filter(l=>l.tag==='label'&&l.attrs.for===a.id).map(nodeText).join(' ').trim();let p=n.parent;while(!text&&p){if(p.tag==='label')text=nodeText(p);p=p.parent}if(!text&&n.tag==='input'&&a.type==='image')text=a.alt?.trim()??'';if(!text&&['submit','reset','button'].includes(a.type))text=a.value?.trim()??'';if(!text)issues.push('Formularfeld '+(i+1)+' ohne erkennbaren Namen')});
 if(rule==='heading-order'){let last=0;for(const n of nodes.filter(n=>/^h[1-6]$/.test(n.tag))){const level=Number(n.tag[1]);if((last===0&&level!==1)||(last&&level>last+1))issues.push('Überschriftensprung '+last+' → '+level);last=level}}
 if(rule==='contrast'){const lum=color=>{let s=color.slice(1);if(s.length===3)s=[...s].map(x=>x+x).join('');const a=[0,2,4].map(i=>parseInt(s.slice(i,i+2),16)/255).map(x=>x<=0.04045?x/12.92:((x+0.055)/1.055)**2.4);return a[0]*0.2126+a[1]*0.7152+a[2]*0.0722};const a=lum(c.foreground),b=lum(c.background),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);if(ratio<c.minContrast)issues.push('Kontrast '+ratio.toFixed(2)+' < '+c.minContrast)}add(rule,issues)}return out;
}
export function checkSecurity(input,rules){let nodes;const getNodes=()=>nodes??=(/<[A-Za-z]/.test(input)?parseHTML(input).nodes:[]);return rules.map(rule=>{let hits=[];const match=re=>{for(const m of input.matchAll(re))hits.push({offset:m.index,match:m[0].slice(0,150)});};switch(rule){case'script-tags':match(/<\s*script\b/gi);break;case'event-handlers':for(const n of getNodes())for(const [key,value]of Object.entries(n.attrs))if(/^on[a-z]/.test(key))hits.push({tag:n.tag,attribute:key,value});break;case'javascript-urls':for(const n of getNodes())for(const [key,value]of Object.entries(n.attrs))if(['href','src','action','formaction','xlink:href'].includes(key)&&/^javascript:/i.test(value.replace(/[\u0000-\u0020]/g,'')))hits.push({tag:n.tag,attribute:key,value});break;case'path-traversal':match(/\.\.[/\\]/g);break;case'eval-calls':match(/\beval\s*\(/g);break;case'xxe':match(/<!ENTITY/gi);break;case'prototype-keys':match(/\b(?:__proto__|constructor|prototype)\b/g);break;case'sql-patterns':match(/\b(?:union\s+select|drop\s+table)\b/gi);break;default:throw Error('Regel unbekannt')}return {rule,passed:hits.length===0,hits}})}
