import crypto from 'node:crypto';
export function instantiatePreset(preset,project,options={}){
 const mode=options.mode??'manual';if(!['manual','command'].includes(mode))throw Error('Prüfmodus ungültig');
 if(!project||!project.target?.trim()||!project.candidate?.trim())throw Error('Testumgebung braucht Ziel und Kandidatenidentität. Unter Projekte & Einstellungen ergänzen.');
 const suffix=crypto.randomUUID().slice(0,8),base=preset.id.toLowerCase()+'-'+suffix;
 const cases=[{id:'positive',name:'Erfolgsfall',steps:[preset.positive,'Unabhängigen Sollwert vor der Ausführung festhalten.','Tatsächlichen Einstieg und Zielzustand beobachten; verwendete Fixtures benennen.'],expected:preset.oracle},{id:'negative',name:'Gegenprobe',steps:[preset.negative,'Nur einen isolierten Testbestand gezielt verletzen; Produktbestand nicht unkontrolliert ändern.','Prüfen, dass der konkrete fehlerhafte Fall erkannt wird; Ergebnis und unveränderten Fremdbestand lesen.'],expected:'Die definierte Vertragsverletzung wird durch den zugehörigen Test erkannt; kein Erfolg wegen fehlender Ausführung.'},{id:'readback',name:'Wirkung & Zuordnung',steps:['Ziel '+project.target+' und Kandidat '+project.candidate+' anhand unabhängiger Quelle prüfen.','Ergebnis nach dem vorgesehenen Neustart, Readback oder erneutem Einstieg verifizieren.',preset.scope],expected:'Der tatsächliche Zustand stimmt mit dem unabhängigen Soll überein. Test-ID, Ziel, Kandidat und Aussagegrenze sind eindeutig dokumentiert.'}];
 const variants=options.variants??preset.variants??['Standard'];if(!Array.isArray(variants)||!variants.length||variants.length>10||variants.some(v=>typeof v!=='string'||!v.trim())||new Set(variants).size!==variants.length)throw Error('1–10 eindeutige Varianten erforderlich');
 const tests=variants.flatMap((variant,n)=>cases.map(item=>{let config;const expected='Variante '+variant+': '+item.expected;if(mode==='manual')config={steps:['Variante '+variant+' unabhängig von Nachbarfällen prüfen.',...item.steps],expected};else{const command=options.commands?.[item.id];if(!command?.executable||!Array.isArray(command.args)||!Array.isArray(command.expectedExitCodes))throw Error('Für jeden Fall Programm, Argumentliste und erwartete Exitcodes konfigurieren');config={...command,args:command.args.map(a=>a.replaceAll('{{variant}}',variant))}}
 return {id:base+'-v'+(n+1)+'-'+item.id,name:`${preset.id} · ${preset.name} · ${variant} · ${item.name}`,purpose:preset.purpose,oracle:expected,counterexamples:preset.negative,scope:preset.scope,source:preset.source,type:mode,category:preset.category,projectId:project.id,tags:[preset.id,preset.group,variant,item.id],enabled:true,timeoutMs:options.timeoutMs??60000,config}}));
 return {tests,suite:{id:base,name:options.name??`${preset.id} · ${preset.name}`,testIds:tests.map(t=>t.id),stopOnFailure:false}};
}
